name: Noso-ToolChain manual build

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'  

      # Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-mod-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-mod-${{ runner.os }}-

      # Build the Go project for Linux
      - name: Build for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o cmd/nosotc-cli

      # Upload the built binary as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nosotc-cli-linux
          path: ./cmd/nosotc-cli

